#ifndef LAPLACIAN_SOLVERS_HPP
#define LAPLACIAN_SOLVERS_HPP

/**
 * @file laplacian_solvers.hpp
 * @brief Core structures, enumerations, and class declarations for numerical Laplace equation solvers.
 * @details This file defines the data frameworks and the template-based solver class used to compute 
 * numerical approximations of the Laplace equation using sequential or parallel execution policies.
 * The implementation of the solver algorithms is contained in the corresponding "laplacian_solvers_implementation.hpp" file.
 * @note The solved problem is of the form -Δu = f(x,y) in a 2D squaredomain, with various boundary conditions (Dirichlet, Neumann, Robin).
 */

#include <iostream>
#include <cmath>
#include <vector>
#include <fstream>
#include <Eigen/Dense>
#include <chrono>
#include <mpi.h>
#include <omp.h>
#include <algorithm>

// Use row major eigen matrixes for better performance in parallelism
using eigenMatrix = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;


/**
 * @enum SolverType
 * @brief Specifies the iterative numerical algorithm used to solve the linear system.
 */
enum class SolverType {
    JACOBI,
    SCHWARZ
};  

/**
 * @enum BoundaryCondition
 * @brief Specifies the physical boundary condition type applied to the domain edges.
 */
enum class BoundaryCondition {
    DIRICHLET,
    NEUMANN,
    ROBIN
};

/**
 * @enum ExecutionMode
 * @brief Specifies the execution policy of the solver (sequential or parallel).
 */
enum class ExecutionMode {
    SEQUENTIAL,
    PARALLEL
};

/**
 * @struct Data_Struct
 * @brief Holds geometric parameters, discretization data, source terms, boundary functions, and the exact solution.
 * 
 * @tparam funcType Callable type used for the source term, boundary functions, and exact solution.
 */
template <typename funcType>
struct Data_Struct {
    unsigned n; 
    double x1, x2; 

    funcType f0;  // Source term
    funcType f1;  //BC bottom edge
    funcType f2;  //BC right edge
    funcType f3;  //BC top edge
    funcType f4;  //BC left edge
    funcType u_exact_lambda;
    double tolerance;
    unsigned max_iterations;
    double alpha; // Parameter for Robin boundary condition: gamma*u + du/dn = g
};

/**
 * @struct Result_Struct
 * @brief Contains the output data generated by a single numerical simulation run.
 */
struct Result_Struct {
    eigenMatrix X;
    eigenMatrix Y;
    eigenMatrix u_h; 
    unsigned iterations;
    double iterartion_residue = -1.; // Initial value. If the residue is -1 the solver was not called
};

/**
 * @struct Convergence_Struct
 * @brief Stores collected benchmark metrics across multiple grid refinement levels.
 * 
 * Tracks L2 errors, iteration counts, and computational times for both serial and parallel
 * runs to facilitate convergence order verification and speedup analysis.
 */
struct Convergence_Struct {
    std::vector<double> errors_L2_serial;
    std::vector<double> errors_L2_parallel; 
    std::vector<unsigned> n;
    std::vector<double> iterations_serial;
    std::vector<double> iterations_parallel;
    std::vector<double> times_serial;
    std::vector<double> times_parallel;
};

namespace laplacian_solvers {

    /**
     * @class Laplacian_Solver
     * @brief Template-driven class for assembling and solving the 2D Laplace/Poisson equation.
     * 
     * Leverages template parameters to statically specialize the linear solver algorithm, 
     * boundary condition handling, and parallelization strategy at compile time.
     * 
     * @tparam solver_type The iterative linear solver choice (JACOBI, SCHWARZ).
     * @tparam boundary_condition The applied physical boundary condition type (DIRICHLET, NEUMANN, ROBIN).
     * @tparam execution_mode The computational runtime policy (SEQUENTIAL, PARALLEL).
     * @tparam funcType Callable type (lambda) for the source term g(x,y) and the boundary conditions.

     */
    template <SolverType solver_type, BoundaryCondition boundary_condition, ExecutionMode execution_mode, typename funcType>
    class Laplacian_Solver {
        private:
            Data_Struct<funcType> data; ///< Configuration of the problem and parameters.
            eigenMatrix meshX;    ///< Matrix containing the X coordinates of the structured grid.
            eigenMatrix meshY;    ///< Matrix containing the Y coordinates of the structured grid.
            double h;             ///< Uniform grid spacing parameter h.
            eigenMatrix u_exact;  ///< Analytical solution over the mesh points matrix.
            eigenMatrix u_h; ///< Numerical solution matrix 
            Result_Struct result; ///< Struct to hold the final results of the solver.

            
        public:
        
            /**
             * @brief Constructs a new Laplacian Solver instance.
             * @param d Constant reference to the input data structure defining the problem parameters.
             * @note Initializes grid coordinates, computes exact solution matrix, and pre-applies 
             *       Dirichlet conditions if statically configured.
             */
            Laplacian_Solver(const Data_Struct<funcType>& d); //OK

            /**
             * @brief Dispatches the computation to the correct solver branch based on ExecutionMode.
             * @return Result_Struct Containing the final generated mesh, solution matrix, and total iteration count.
             * @note Solver Structure: sequential / parallel  -->  Jacobi / Schwarz  -->  dirichlet / neumann / robin
             */
            Result_Struct solve(); //OK

            /**
             * @brief Runs an automated convergence test across multiple mesh refinement levels.
             * @details Computes relative L2 errors against the analytical solution, benchmarks sequential 
             *          vs parallel execution times, and stores iteration patterns.
             * @return Convergence_Struct.
             */
            Convergence_Struct convergence_test(); 

            /**
             * @brief Prints the mesh, discrete solution, and exact solution to the standard output.
             */
            void print() const;

            /**
             * @brief Exports the structured mesh and solution data into legacy VTK format.
             * @details Visualizable using ParaView.
             * @param meshX Matrix containing coordinates along X axis.
             * @param meshY Matrix containing coordinates along Y axis.
             * @param u_h Final discrete simulation results matrix.
             * @param filename Target path/name of the generated file.
             */
            void export_to_vtk(const eigenMatrix& meshX, const eigenMatrix& meshY, const eigenMatrix& u_h, const std::string& filename) const;

            void build_mesh(); //OK

            private:
            // PRIVATE HELPER METHODS

            // Mesh and exact solution builders
            
            void build_mesh_sequential(); //OK
            void build_mesh_parallel(); //OK
            
            void build_exact_solution(); //OK
            void build_exact_solution_sequential(); //OK
            void build_exact_solution_parallel(); //OK

            // Print and postprocessing
            void print_mesh() const; //OK
            void print_solution() const; //OK
            void print_exact_solution() const; //OK

            //SOLVER STRUCTURE: sequential / parallel -> jacobi / schwarz -> dirichlet / neumann / robin
            Result_Struct sequential_solve(); //OK
            Result_Struct parallel_solve(); //OK

            Result_Struct jacobi_sequential(); //OK
            Result_Struct jacobi_parallel(); //OK
            Result_Struct schwarz_parallel(); //OK
 
            Result_Struct jacobi_sequential_dirichlet(); //OK
            Result_Struct jacobi_sequential_neumann(); //OK
            Result_Struct jacobi_sequential_robin(); //OK
            Result_Struct jacobi_parallel_dirichlet();//OK
            Result_Struct jacobi_parallel_neumann();
            Result_Struct jacobi_parallel_robin();
            Result_Struct schwarz_parallel_dirichlet();//OK
            Result_Struct schwarz_parallel_neumann();
            Result_Struct schwarz_parallel_robin();

    };

} // namespace laplacian_solvers

#include "laplacian_solvers_implementation.hpp"
#include "laplacian_solvers_postprocessing.hpp"
#include "laplacian_solvers_initializer.hpp"
#include "laplacian_solvers_sequential_implementations.hpp"

#endif 