#ifndef LAPLACIAN_SOLVERS_HPP
#define LAPLACIAN_SOLVERS_HPP

/**
 * @file laplacian_solvers.hpp
 * @brief Core structures, enumerations, and class declarations for numerical Laplace equation solvers.
 * @details This file defines the data frameworks and the template-based solver class used to compute 
 * numerical approximations of the Laplace equation using sequential or parallel execution policies.
 * The implementation of the solver algorithms is contained in the corresponding "laplacian_solvers_implementation.hpp" file.
 */

#include <iostream>
#include <cmath>
#include <vector>
#include <fstream>
#include <Eigen/Dense>
#include <chrono>

/**
 * @enum SolverType
 * @brief Specifies the iterative numerical algorithm used to solve the linear system.
 */
enum class SolverType {
    JACOBI,
    SCHWARZ
};  

/**
 * @enum BoundaryCondition
 * @brief Specifies the physical boundary condition type applied to the domain edges.
 */
enum class BoundaryCondition {
    DIRICHLET,
    NEUMANN,
    ROBIN
};

/**
 * @enum ExecutionMode
 * @brief Specifies the execution policy of the solver (sequential or parallel).
 */
enum class ExecutionMode {
    SEQUENTIAL,
    PARALLEL
};

/**
 * @struct Data_Struct
 * @brief Holds geometric parameters, discretization data, source terms, and the exact solution.
 * 
 * @tparam Func0 Callable type (lambda) for the source term.
 * @tparam Func1 Callable type (lambda) for the boundary condition or source term on edge 1.
 * @tparam Func2 Callable type for the boundary condition or source term on edge 2.
 * @tparam Func3 Callable type for the boundary condition or source term on edge 3.
 * @tparam Func4 Callable type for the boundary condition or source term on edge 4.
 * @tparam u_ex Callable type for the exact analytical solution, used for convergence verification.
 */
template <typename Func0,typename Func1, typename Func2, typename Func3, typename Func4, typename u_ex>
struct Data_Struct {
    unsigned n; 
    double x1, x2; 

    Func0 f0;  // Source term
    Func1 f1;  //BC bottom edge
    Func2 f2;  //BC right edge
    Func3 f3;  //BC top edge
    Func4 f4;  //BC left edge
    u_ex u_exact_lambda;
    double tolerance;
    unsigned max_iterations;
    double gamma; // Parameter for Robin boundary condition: gamma*u + du/dn = g
};

/**
 * @struct Result_Struct
 * @brief Contains the output data generated by a single numerical simulation run.
 */
struct Result_Struct {
    Eigen::MatrixXd MESH;
    Eigen::MatrixXd u_h; 
    unsigned iterations;

};

/**
 * @struct Convergence_Struct
 * @brief Stores collected benchmark metrics across multiple grid refinement levels.
 * 
 * Tracks L2 errors, iteration counts, and computational times for both serial and parallel
 * runs to facilitate convergence order verification and speedup analysis.
 */
struct Convergence_Struct {
    std::vector<double> errors_L2_serial;
    std::vector<double> errors_L2_parallel; 
    std::vector<unsigned> n;
    std::vector<double> iterations_serial;
    std::vector<double> iterations_parallel;
    std::vector<double> times_serial;
    std::vector<double> times_parallel;
};

namespace laplacian_solvers {

    /**
     * @class LaplacianSolver
     * @brief Template-driven class for assembling and solving Laplace equation.
     * 
     * Leverages template parameters to statically specialize the linear solver algorithm, 
     * boundary condition handling, and parallelization strategy at compile time.
     * 
     * @tparam solver_type The iterative linear solver choice (JACOBI, SCHWARZ).
     * @tparam boundary_condition The applied physical boundary condition type (DIRICHLET, NEUMANN, ROBIN).
     * @tparam execution_mode The computational runtime policy (SEQUENTIAL, PARALLEL).
     */
    template <SolverType solver_type, BoundaryCondition boundary_condition, ExecutionMode execution_mode,
              typename Func0, typename Func1, typename Func2, typename Func3, typename Func4, typename u_ex>
    class Laplacian_Solver {
        private:
            Data_Struct<Func0, Func1, Func2, Func3, Func4, u_ex> data;
            Eigen::MatrixXd meshX;
            Eigen::MatrixXd meshY;
            double h;
            Eigen::MatrixXd u_h;
            Eigen::MatrixXd u_exact;
            
        public:
        
            /**
            * @brief Constructs a new Laplacian Solver instance.
             * @param data Constant reference to the input data structure defining the problem parameters.
            */
            Laplacian_Solver(const Data_Struct<Func0, Func1, Func2, Func3, Func4, u_ex>& d) : data(d) {}; //OK

            /**
             * @brief Executes the numerical simulation for the specific template configuration.
             * 
             * Assembles the discrete system and iterates according to the selected numerical schemes.
             * 
             * @return Result_Struct Output structure containing the mesh, discrete solution u_h, and total iterations.
             */
            Result_Struct solve(); //OK

            /**
             * @brief Executes the numerical simulation for the specific template configuration.
             * 
             * Assembles the discrete system and iterates according to the selected numerical schemes.
             * 
             * @return Result_Struct Output structure containing the mesh, discrete solution u_h, and total iterations.
             */
            Convergence_Struct convergence_test(); 

            void print();
            void export_to_vtk(const Eigen::MatrixXd& meshX, const Eigen::MatrixXd& meshY, const Eigen::MatrixXd& u_h, const std::string& filename);

            private:
            // Private helper methods

            //SOLVER STRUCTURE: sequential / parallel -> jacobi / schwarz -> dirichlet / neumann / robin
            Result_Struct sequential_solve(); //OK
            Result_Struct parallel_solve(); //OK

            Result_Struct jacobi_sequential(); //OK
            Result_Struct jacobi_parallel(); //OK
            Result_Struct schwarz_sequential(); //OK
            Result_Struct schwarz_parallel(); //OK
 
            Result_Struct jacobi_sequential_dirichlet();
            Result_Struct jacobi_sequential_neumann();
            Result_Struct jacobi_sequential_robin();
            Result_Struct jacobi_parallel_dirichlet();
            Result_Struct jacobi_parallel_neumann();
            Result_Struct jacobi_parallel_robin();
            Result_Struct schwarz_sequential_dirichlet();
            Result_Struct schwarz_sequential_neumann();
            Result_Struct schwarz_sequential_robin();
            Result_Struct schwarz_parallel_dirichlet();
            Result_Struct schwarz_parallel_neumann();
            Result_Struct schwarz_parallel_robin();

    };

} // namespace laplacian_solvers

#include "laplacian_solvers_implementation.hpp"

#endif 